embedder_config:
  backend: HF
  params:
    model_name: sentence-transformers/all-mpnet-base-v2
    encode_kwargs: 
      normalize_embeddings: False

retriever_config:
  similarity_top_k: 3
  similarity_threshold: 0.4

llm_config:
  knowledge_chain:
    model_name: llama3.1:70b
    temperature: 0.4
  conversation_chain:
    model_name: llama3.1:8b
    temperature: 0.4
  grader_chain:
    model_name: llama3.1:8b
    temperature: 0.4
  eval_chain:
    model_name: llama3.1:8b
    eval_metrics:
      - correctness
      - relevance
      - harmfulness
      - conciseness
      - coherence

database:
  uri : 
  

